hadoop-bin:
	#https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html#Pseudo-Distributed_Operation
	wget https://dlcdn.apache.org/hadoop/common/hadoop-3.3.4/hadoop-3.3.4.tar.gz
	tar -zxvf ./hadoop-3.3.4.tar.gz

hive-bin:
	wget https://dlcdn.apache.org/hive/hive-3.1.3/apache-hive-3.1.3-bin.tar.gz
	tar -zxvf apache-hive-3.1.3-bin.tar.gz